### ISSUE TITLE
The start method completion closure is not executed

### ISSUE THREAD

**Issue by cheyongzi** [gaetanzanella/swift-ssh-client#19]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/8185484/221329212-73c65378-cf44-41cf-be12-2d8c35936430.png">

I connected to the server with an account and password, but the completion did not call back the notification

**Comment by cheyongzi** [comment]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/8185484/221333369-ab8d050a-09a1-42c2-85b6-be6e24464ec4.png">

I found that after the connection is successful, only the internalState is set to authenticating and return none

**Comment by gaetanzanella** [comment]
Hi @cheyongzi is it the same problem? 

https://github.com/gaetanzanella/swift-ssh-client/issues/16

Maybe we should change this behavior. It is possible. But capturing self seems a bit weird to me as you need to close your connection at some point.

**Comment by cheyongzi** [comment]
@gaetanzanella  it is the same problem
