### ISSUE TITLE
Don't get the response data  SSHCommand

### ISSUE THREAD

**Issue by ghost** [gaetanzanella/swift-ssh-client#25]
I'm trying to create a project (this is my first BIG swift project)I will be able to connect to my raspberryPi (my server in this project) (ssh connection looks good)
and do these functions: 
fetch(currentDirectory: String) - get a list of all files and folders names  and a date of the last time they were modified in currentDirectory in the server.

delete(currentDirectory: String, fileName:String) - delete a file/folder by its name that is in currentDirectory in the server.

upload(LocalPath: String, serverPath:String) - upload file from client to server

download(LocalPath: String, serverPath:String) - download file from server to  client

For start im trying to build my fetch function using SSHCommand that you created in SSHClient package, but I don't get the data in the response, not even when I'm trying to run this code with the command "echo Hello \n" as Ive seen in the readme of the project

<img width="1440" alt="Screenshot 2023-12-07 at 02 36 05" src="https://github.com/gaetanzanella/swift-ssh-client/assets/152722993/ca804748-678c-4033-a70f-2c8ed4790201">

If Im wrong and didn't understood how to use it, please correct me.
If you have any idea how to use this package to create the functions I mentioned before, I'll be glad for help too
Thanks in advance,

**Comment by gaetanzanella** [comment]
Hi @yoavscode, yes dont forget to add \n at the end of your msg.

But it sounds like you have some data in your response:
```swift
response.standardOutput // here
```
